name: 'New Flow With Input'

env:
  IS_DATA: "true"
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      send_to_datadog:
        description: 'Send to Datadog (true/false)'
        required: false
        default: 'true'

jobs:
  gen-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: Build application
        run: |
          mkdir -p ./logs
          make build | tee -a ./logs/build.log
          
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '^1.17.7'

      - name: 'Generate Readme'
        run: go run scripts/generate.go readme

        

      - name: 'Validate Diff'
        run: |
          STATUS=$(git status --porcelain)
          if [[ -n "$STATUS" ]]; then
            echo "ERROR: README has not been updated"
            echo ""
            echo "Run the following command to update the README: go run scripts/generate.go readme"
            exit 1
          fi

      - name: 'Upload Logs'
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs
          path: ./logs/

  export-and-send-logs:
    runs-on: ubuntu-latest
    needs: gen-readme
    permissions:
      actions: read  # Required to fetch workflow logs
    steps:
      - name: 'Download Logs'
        uses: actions/download-artifact@v4
        with:
          name: workflow-logs
          path: ./logs/

      - name: 'Send Logs to Datadog'
        run: |
          for log_file in ./logs/*; do
            curl -X POST "https://http-intake.logs.datadoghq.com/v1/input" \
              -H "Content-Type: text/plain" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              --data-binary @"$log_file"
          done
